//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holidays.Model.Entites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HolidaysDBEntities : DbContext
    {
        public HolidaysDBEntities()
            : base("name=HolidaysDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUser { get; set; }
        public virtual DbSet<CarInfo> CarInfo { get; set; }
        public virtual DbSet<HomeData> HomeData { get; set; }
        public virtual DbSet<HouseConfigure> HouseConfigure { get; set; }
        public virtual DbSet<HouseEvaluate> HouseEvaluate { get; set; }
        public virtual DbSet<HouseImg> HouseImg { get; set; }
        public virtual DbSet<HouseInfo> HouseInfo { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<OrderItem> OrderItem { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductInfo> ProductInfo { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<SpotInfo> SpotInfo { get; set; }
        public virtual DbSet<SystemConfig> SystemConfig { get; set; }
        public virtual DbSet<TenantInfo> TenantInfo { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserFavorite> UserFavorite { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserInfoCertificate> UserInfoCertificate { get; set; }
        public virtual DbSet<UserInfoExt> UserInfoExt { get; set; }
        public virtual DbSet<UserOrderRecord> UserOrderRecord { get; set; }
        public virtual DbSet<HouseInfoView> HouseInfoView { get; set; }
        public virtual DbSet<OrderInfoView> OrderInfoView { get; set; }
        public virtual DbSet<UserFavoriteView> UserFavoriteView { get; set; }
        public virtual DbSet<UserInfoCertificateView> UserInfoCertificateView { get; set; }
        public virtual DbSet<UserInfoExtView> UserInfoExtView { get; set; }
        public virtual DbSet<UserInfoView> UserInfoView { get; set; }
        public virtual DbSet<ShopCategory> ShopCategory { get; set; }
        public virtual DbSet<ShopInfo> ShopInfo { get; set; }
        public virtual DbSet<ShopInfoCertificate> ShopInfoCertificate { get; set; }
        public virtual DbSet<ShopInfoCertificateView> ShopInfoCertificateView { get; set; }
        public virtual DbSet<HouseComment> HouseComment { get; set; }
        public virtual DbSet<HouseEvaluateView> HouseEvaluateView { get; set; }
        public virtual DbSet<SysLog> SysLog { get; set; }
        public virtual DbSet<User> T_User { get; set; }
        public virtual DbSet<Role> T_Role { get; set; }
        public virtual DbSet<Permission> T_Permission { get; set; }
        public virtual DbSet<Function> T_Function { get; set; }
        public virtual DbSet<FuncPermission> T_FuncPermission { get; set; }
        public virtual DbSet<UserRole> T_UserRole { get; set; }
        public virtual DbSet<ShopToDayPrice> ShopToDayPriceSet { get; set; }
    }
}
