//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holidays.Model.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseComment
    {
        public long ID { get; set; }
        public long HouseInfoId { get; set; }
        public long EvaluateId { get; set; }
        public long ToUserId { get; set; }
        public string ToUserName { get; set; }
        public long FromUserId { get; set; }
        public string FromUserName { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string Comments { get; set; }
    }
}
