//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holidays.Model.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseEvaluateView
    {
        public long ID { get; set; }
        public long HouseInfoID { get; set; }
        public long UserInfoID { get; set; }
        public string UserPhone { get; set; }
        public int CleanScore { get; set; }
        public int LocationScore { get; set; }
        public int EnvironmentScore { get; set; }
        public int ServiceScore { get; set; }
        public int PerformanceScore { get; set; }
        public double AverageScore { get; set; }
        public string EvaluateContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int State { get; set; }
        public string Username { get; set; }
        public string UserImg { get; set; }
        public string HouseTitle { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<int> DecorativeStyle { get; set; }
        public Nullable<int> LeaseType { get; set; }
        public Nullable<int> BedroomNum { get; set; }
        public Nullable<int> LivingRoomNum { get; set; }
        public Nullable<int> ToiletNum { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsTrusteeship { get; set; }
        public Nullable<bool> IsSell { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<bool> IsCooking { get; set; }
        public Nullable<bool> IsPet { get; set; }
        public Nullable<int> StayPersonNum { get; set; }
        public Nullable<double> HouseSize { get; set; }
        public string Facilities { get; set; }
        public string Address { get; set; }
        public string About { get; set; }
        public string Rules { get; set; }
        public string ChargesNotes { get; set; }
        public string BaseInfo { get; set; }
        public Nullable<bool> IsReals { get; set; }
        public Nullable<int> BuyNum { get; set; }
        public Nullable<int> EvaluateNum { get; set; }
        public Nullable<int> EvaluateAvgScore { get; set; }
        public Nullable<long> ShopId { get; set; }
        public string ShopName { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<long> FromUserId { get; set; }
        public string FromUserName { get; set; }
    }
}
