//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holidays.Model.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseEvaluate
    {
        public long ID { get; set; }
        public long HouseInfoID { get; set; }
        public long UserInfoID { get; set; }
        public string UserPhone { get; set; }
        public int CleanScore { get; set; }
        public int LocationScore { get; set; }
        public int EnvironmentScore { get; set; }
        public int ServiceScore { get; set; }
        public int PerformanceScore { get; set; }
        public double AverageScore { get; set; }
        public string EvaluateContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int State { get; set; }
        public string HouseTitle { get; set; }
        public string Username { get; set; }
        public string UserImg { get; set; }
    }
}
