//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holidays.Model.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public long ID { get; set; }
        public string ProductName { get; set; }
        public long CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Price { get; set; }
        public bool IsHomeShow { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string ProductImg { get; set; }
        public string HomeImg { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
    }
}
