//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holidays.Model.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopInfo
    {
        public long ID { get; set; }
        public string ShopName { get; set; }
        public string Locations { get; set; }
        public Nullable<decimal> Scores { get; set; }
        public Nullable<decimal> StartPrice { get; set; }
        public Nullable<long> ShopType { get; set; }
        public string Tags { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> SpotId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<long> SortBy { get; set; }
        public string ShopImgs { get; set; }
        public string ShopTypeName { get; set; }
        public string SpotName { get; set; }
        public string PhoneNo { get; set; }
        public string UserName { get; set; }
        public string DecorativeStyle { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<int> IsCheck { get; set; }
        public string About { get; set; }
        public string Rules { get; set; }
        public string ChargesNotes { get; set; }
    }
}
