//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holidays.Model.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoExt
    {
        public long ID { get; set; }
        public int IsCertification { get; set; }
        public long UserInfoID { get; set; }
        public string IDCardImg1 { get; set; }
        public string IDCardImg2 { get; set; }
        public string HouseAddress { get; set; }
        public string Housecertificate { get; set; }
        public string WeixinAccount { get; set; }
        public string AlipayAccount { get; set; }
    }
}
