//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holidays.Model.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoView
    {
        public long ID { get; set; }
        public long AccountID { get; set; }
        public string Img { get; set; }
        public string Nikename { get; set; }
        public string Username { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string PhoneNo2 { get; set; }
        public string IDCardNo { get; set; }
        public int UserType { get; set; }
        public Nullable<int> IsRealName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int State { get; set; }
        public string PhoneAccount { get; set; }
        public string UserToken { get; set; }
        public string WeixinUnionid { get; set; }
        public string LoginAccount { get; set; }
        public string LoginPwd { get; set; }
        public string IDCardImg1 { get; set; }
        public string IDCardImg2 { get; set; }
        public string HouseAddress { get; set; }
        public string Housecertificate { get; set; }
        public Nullable<int> IsCertification { get; set; }
        public string AlipayAccount { get; set; }
        public string WeixinAccount { get; set; }
    }
}
